# Generated by Django 4.1.7 on 2023-03-17 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_player'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='connected_players',
            field=models.ManyToManyField(blank=True, related_name='connected_players', to='chat.player'),
        ),
    ]
